GraphicTestCore/Controllers/AppController.cs
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OfficeOpenXml;

namespace qBIPro.Controllers
{
    [Authorize]
    public class AppController : Controller
    {
        
        public IActionResult Data()
        {
            return View();
        }

        [IgnoreAntiforgeryTokenAttribute]
        public async Task<ActionResult> OnPost()
        {

            IFormFile file = Request.Form.Files[0];
            var filePath = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());

            if (file.Length > 0)
            {
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
            }
            FileInfo fileinfo = new FileInfo(filePath);
            StringBuilder sb = new StringBuilder();
            using (ExcelPackage package = new ExcelPackage(fileinfo))
            {

                ExcelWorksheet worksheet = package.Workbook.Worksheets.FirstOrDefault();
                DataTable excel = GetDataTableFromExcel(worksheet, true);
                string json = JsonConvert.SerializeObject(excel, Formatting.Indented);

                return Content(ConvertDataTableToHTML(excel));
                //return Json(json);
            }
        }

        private static string ConvertDataTableToHTML(DataTable dt)
        {
            string html = "<table class='table table-striped table-responsive'>";
            //add header row
            html += "<tr>";
            for (int i = 0; i < dt.Columns.Count; i++)
                html += "<td>" + dt.Columns[i].ColumnName + "</td>";
            html += "</tr>";
            //add rows
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                html += "<tr>";
                for (int j = 0; j < dt.Columns.Count; j++)
                    html += "<td>" + dt.Rows[i][j].ToString() + "</td>";
                html += "</tr>";
            }
            html += "</table>";
            return html;
        }

        public static DataTable GetDataTableFromExcel(ExcelWorksheet ws, bool hasHeaderRow = true)
        {
            var tbl = new DataTable();
            foreach (var firstRowCell in ws.Cells[1, 1, 1, ws.Dimension.End.Column])
                tbl.Columns.Add(hasHeaderRow ?
                    firstRowCell.Text : string.Format("Column {0}", firstRowCell.Start.Column));
            var startRow = hasHeaderRow ? 2 : 1;
            for (var rowNum = startRow; rowNum <= ws.Dimension.End.Row; rowNum++)
            {
                var wsRow = ws.Cells[rowNum, 1, rowNum, ws.Dimension.End.Column];
                var row = tbl.NewRow();
                foreach (var cell in wsRow)
                {
                        row[cell.Start.Column - 1] = cell.Text;
                }

                tbl.Rows.Add(row);
            }
            return tbl;
        }

        public IActionResult Preview()
        {
            return View();
        }

        public IActionResult Graphs()
        {
            return View();
        }

        public IActionResult Maps()
        {
            return View();
        }
    }
}

GraphicTestCore/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using qBI.Areas.Identity;
using qBIPro.Data;
using qBIPro.Models;

namespace qBI.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _userContext;
        private readonly AppUserManager _appUserManager;
        //private IHostingEnvironment _hostingenvironment;
        //IHostingEnvironment _env;
        public CustomersController(ApplicationDbContext context, AppUserManager appUserManager)
        {
            _userContext = context;
            _appUserManager = appUserManager;
        }
        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var user = await _appUserManager.GetUserAsync(User);

            var viewModel = from o in _userContext.Customers
                            join o2 in _userContext.Addresses 
                            on o.CustomerId equals o2.CustomerId
                            where o.CustomerId.Equals(o2.CustomerId)
                            where o.AreaId.Equals(user.AreaId)
                            select new CustomerDetails { Customer = o, Addresses = o2 };

            return View(viewModel);
          //  return View(_userContext.Customers.ToList());
        }

        public IActionResult Create(CustomerDetails customerDetails)
        {

            return View(customerDetails);


        }
        [HttpPost]
        public async Task<IActionResult> CreateCustomer(CustomerDetails customerDetails)
        {
            if(ModelState.IsValid)
            {
                    var user = await  _appUserManager.GetUserAsync(User);
                    customerDetails.Customer.AreaId = user.AreaId;
                    await _userContext.AddAsync(customerDetails.Customer);
                    customerDetails.Addresses.CustomerId = customerDetails.Customer.CustomerId;
                    await _userContext.AddAsync(customerDetails.Addresses);
                    await _userContext.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Policy = "CustomerArea")]
        public async Task<IActionResult> Details(int Id)
        {
            CustomerDetails customerDetails = await getCustomerDetails(Id);

            return View(customerDetails);


        }

        [Authorize(Policy = "CustomerArea")]
        public async Task<IActionResult> Edit(int Id)
        {
            CustomerDetails customerDetails = await getCustomerDetails(Id);


            return View(customerDetails);
        }
        private async Task<CustomerDetails> getCustomerDetails(int Id)
        {
            var customer = await _userContext.Customers.FindAsync(Id);
            CustomerDetails customerDetails = new CustomerDetails();
            customerDetails.Customer = customer;
            string query = "SELECT * FROM Addresses WHERE CustomerId = {0}";
            customerDetails.Addresses = await _userContext.Addresses
                .FromSql(query, customer.CustomerId)
                .SingleOrDefaultAsync();
            return customerDetails;
        }

        public async Task<IActionResult> Save(CustomerDetails customerDetails)
        {


            if (ModelState.IsValid)
            {
                Address address = customerDetails.Addresses;
                Customer customer = customerDetails.Customer;

                _userContext.Update(address);
                _userContext.Update(customer);

                await _userContext.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));


        }

        [Authorize(Policy = "CustomerArea")]
        public async Task<IActionResult> Delete(int Id)
        {

            var customer = await _userContext.Customers.FindAsync(Id);
            if (ModelState.IsValid)
            {
                _userContext.Remove(customer);
                await _userContext.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));


        }


    }
}

GraphicTestCore/Controllers/WebScrapeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using HtmlAgilityPack;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using qBI.Models;
using qBIPro.Data;


namespace qBIPro.Controllers
{
    [Authorize]
    public class WebScrapeController : Controller
    {
        private readonly ApplicationDbContext _context;
        public WebScrapeController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: WebScrape
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Scrape(string Url)
        {
            if (Url.StartsWith("http://", StringComparison.InvariantCultureIgnoreCase))
            {
                Url = Url.Remove(0, 7);

            }
            else if(Url.StartsWith("https://", StringComparison.InvariantCultureIgnoreCase))
            {
                Url = Url.Remove(0, 8);

            }
            if (Url.StartsWith("www.", StringComparison.InvariantCultureIgnoreCase))
            {
                Url = Url.Remove(0, 4);
            }



            HttpClient hc = new HttpClient();
            HttpResponseMessage result = await hc.GetAsync($"http://{Url}/");

            Stream stream = await result.Content.ReadAsStreamAsync();

            HtmlDocument doc = new HtmlDocument();

            doc.Load(stream);

            HtmlNodeCollection links = doc.DocumentNode.SelectNodes("//a[@href]");//the parameter is use xpath see: https://www.w3schools.com/xml/xml_xpath.asp 
            HtmlNodeCollection iframes = doc.DocumentNode.SelectNodes("//iframe[@src]");//the parameter is use xpath see: https://www.w3schools.com/xml/xml_xpath.asp 

            //return View(links);
            List<String> html = new List<String>();
            if(links != null)
            foreach (var link in links)
            {
                    string linkTxt = link.GetAttributeValue("href", string.Empty);
                
                if(linkTxt.StartsWith("http") && !linkTxt.Contains(Url))
                {
                        if(linkTxt != null)
                            html.Add(linkTxt);
                }
            }
            if(iframes != null)
            foreach (var iframe in iframes)
            {
                string linkTxt = iframe.GetAttributeValue("src", string.Empty);

                if ((linkTxt.StartsWith("http") || linkTxt.StartsWith("//www")) && !linkTxt.Contains(Url))
                {
                        if (linkTxt != null)
                            html.Add(linkTxt);
                }
            }

            ViewData["Result"] = html;

            return View("Index");
        }


    }
}

GraphicTestCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="description" content="Quick Business Intelligence Professional is an innovative web application that aims to deliver big data analysis
    to your computer.">
    <meta name="keywords" content="qBIPro,BI,Analysis,Data">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script nws-csp-add-nonce="true" async src="https://www.googletagmanager.com/gtag/js?id=UA-113702706-2"></script>
    <script nws-csp-add-nonce="true">
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-113702706-2');
    </script>
    <title>qBIPro.com - @ViewData["Title"]</title>
    <link async rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-expand-md bg-info navbar-dark fixed-top">
        <div class="container">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand mb-0 h1 text-white">           
                qBIPro
            </a>
            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navbarNav">
                <partial name="_LoggedMenuPartial" />
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div>
                <ul class="list-inline">
                    <li class="list-inline-item">2018 - qBIPro</li>
                    <li class="list-inline-item"><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li class="list-inline-item"><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy Policy</a></li>
                    <li class="list-inline-item"><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </footer>
    </div>
    <script src="~/js/jquery331.js"></script>
    <script src="~/js/popper.js"></script>
    <script src="~/js/bootstrap411.js"></script>
    <!-- <script defer src="~/js/fontsawesome.js"></script>-->
    @RenderSection("Scripts", required: false)
</body>
</html>

GraphicTestCore/Views/Shared/_LoggedMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using qBI.Models;
@using qBI.Areas.Identity;
@inject AppSignInManager SignInManager
@inject AppUserManager UserManager

@if (SignInManager.IsSignedIn(User))
{
<ul class="navbar-nav mr-auto">
    <li class="nav-item"><a class="nav-link text-white" asp-area="" asp-controller="App" asp-action="Data">Data</a></li>
    <li class="nav-item"><a class="nav-link text-white" asp-area="" asp-controller="Customers" asp-action="">Customers</a></li>
    <li class="nav-item"><a class="nav-link text-white" asp-area="" asp-controller="WebScrape" asp-action="">Web scraper</a></li>
    @*<li class="nav-item"><a class="nav-link text-white" asp-area="" asp-controller="App" asp-action="Graphs">Graphs</a></li>
        <li class="nav-item"><a class="nav-link text-white" asp-area="" asp-controller="App" asp-action="Maps">Maps</a></li>*@
    @if (User.IsInRole("Admin"))
    {
        <li class="nav-item"><a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="Index">Admin panel</a></li>
    }
</ul>
}
else
{

}